In [ ]:
 import tensorflow as tf 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Input, Dense 
import numpy as np

In [ ]:
x = np.array([[0,0], [0,1], [1,0], [1,1]], "uint8") 
y  = np.array([[0], [0], [0], [1]], "uint8")

In [ ]:
model = Sequential() 
model.add(Dense(units=1, activation='sigmoid', input_dim=2))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x, y, epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 820ms/step - loss: 0.7347 - accuracy: 0.5000
Epoch 2/50
1/1 [==============================] - 0s 6ms/step - loss: 0.7344 - accuracy: 0.5000
Epoch 3/50
1/1 [==============================] - 0s 7ms/step - loss: 0.7340 - accuracy: 0.5000
Epoch 4/50
1/1 [==============================] - 0s 10ms/step - loss: 0.7337 - accuracy: 0.5000
Epoch 5/50
1/1 [==============================] - 0s 10ms/step - loss: 0.7334 - accuracy: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 15ms/step - loss: 0.7330 - accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 5ms/step - loss: 0.7327 - accuracy: 0.5000
Epoch 8/50
1/1 [==============================] - 0s 4ms/step - loss: 0.7323 - accuracy: 0.5000
Epoch 9/50
1/1 [==============================] - 0s 10ms/step - loss: 0.7320 - accuracy: 0.5000
Epoch 10/50
1/1 [==============================] - 0s 5ms/step - loss: 0.7316 - accuracy: 0.5000
Epoch 11/50
1/1 [================

In [ ]:
print(model.layers[0].get_weights())

[array([[ 0.7626512 ],
       [-0.79132634]], dtype=float32), array([-0.04971416], dtype=float32)]


In [ ]:
model.predict (x)

array([[0.487574  ],
       [0.3013157 ],
       [0.67104983],
       [0.48041272]], dtype=float32)

In [ ]:
x = [[0,0], [0,1], [1,0], [1,1]] 
y = [[0], [1], [1], [0]]

In [ ]:
xor = Sequential() 
xor.add(Dense(2, input_dim=2, activation='sigmoid')) 
xor.add(Dense(1, activation='sigmoid'))
xor.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
xor.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [ ]:
xor.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 464ms/step - loss: 0.7036 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7035 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7033 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.7031 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7030 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7028 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7027 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7025 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.7024 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.7022 - accuracy: 0.5000
Epoch 11/1000
1/1

In [ ]:
xor.get_weights()

[array([[-1.3199544, -0.9340597],
        [-1.5677392, -0.6964174]], dtype=float32),
 array([-0.3244967 , -0.34335122], dtype=float32),
 array([[-0.6344536 ],
        [-0.26934355]], dtype=float32),
 array([0.17496072], dtype=float32)]

In [ ]:
xor.predict(x)

array([[0.44941866],
       [0.5053755 ],
       [0.5033883 ],
       [0.529353  ]], dtype=float32)

In [ ]:
from sklearn.datasets import load_breast_cancer 
Data = load_breast_cancer()

In [ ]:
print (Data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [ ]:
features = Data.data 
target= Data.target
 
print (features.shape) 
print (target.shape)

(569, 30)
(569,)


In [ ]:
from sklearn.model_selection import train_test_split
 
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2)
 
print(x_train.shape) 
 
print(y_test.shape)
 
print(y_train.shape)
 
print(x_test.shape)

(455, 30)
(114,)
(455,)
(114, 30)


In [ ]:
from keras.models import Sequential 
from keras.layers import Dense

In [ ]:
model = Sequential() 
model.add(Dense(32, input_dim = 30, activation='relu')) 
model.add(Dense (64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 32)                992       
_________________________________________________________________
dense_7 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 65        
Total params: 3,169
Trainable params: 3,169
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
 model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
15/15 [==============================] - 7s 2ms/step - loss: 2.0285 - accuracy: 0.6254
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5535 - accuracy: 0.8744
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6527 - accuracy: 0.8084
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 0.4584 - accuracy: 0.8521
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2752 - accuracy: 0.9088
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3039 - accuracy: 0.9157
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2400 - accuracy: 0.9055
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2366 - accuracy: 0.9097
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3236 - accuracy: 0.8919
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.1853 - accuracy: 0.9427


In [ ]:
scores = model.evaluate (x_test, y_test) 
print (scores)

4/4 [==============================] - 1s 3ms/step - loss: 0.2844 - accuracy: 0.8999
[0.25556856393814087, 0.9035087823867798]


In [ ]:
predictions = model.predict (x_test)
label=[]
for pred in predictions:
  if pred>=0.5: 
    print("Malignent")
  else: 
    print("Benign")

Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Malignent
Benign
Benign
Malignent
Benign
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Benign
Benign
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Benign
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Malignent
Benign
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Benign
Benign
Benign
Benign
Benign
Benign
Malignent
Benign
